# Generated by Django 2.1.5 on 2019-01-31 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('file_original', models.FileField(upload_to='')),
                ('file_thumb', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
